### PR TITLE
vendor update; azure-sdk-for-go

### PR DESCRIPTION
**Pull request by tomahawk28**
Toward https://github.com/giantswarm/giantswarm/issues/6925
For updating azure-operator, we need to update e2eclients first.

### CODE REVIEW

**Comment by tomahawk28** [comment]
Can't get a link to @giantswarm/team-batman

**Comment by rossf7** [comment]
@tomahawk28 Check the repo settings. The teams are wrong.

**Review by rossf7 — APPROVED** [review]
LGTM

**Comment by xh3b4sd** [comment]
Just for the record. The mix of different provider specific dependencies is one anti pattern we should try to avoid in the future so that we do not need to deal with Azure dependencies in the `aws-operator` or vice versa. 👍

**Pull request merged**
